[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "prophet"
version = "0.1.0"
authors = [
  {name = "Niels Turley", email = "nturley1@bidmc.harvard.edu"},
]
description = "Electronic health record phenotyping library"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "polars",
    "scikit-learn",
    "nltk",
    "ray",
    "joblib",
    "pyarrow",
    "seaborn",
    "matplotlib",
]

[tool.hatch.build.sources]
"src" = ""

[tool.hatch.build.targets.wheel]
include = ["src/prophet/models/epilepsy/*"]

[project.urls]
"Homepage" = "https://github.com/bdsp-core/prophet/"