# Sample TesterModel Configuration File
# You can comment out or remove sections that aren't needed for your model

# Model metadata
model_path:  # Path to save/load a trained model (optional)
credits:   # Attribution information

# Input data schema 
schema:
  # demo:
  #   id: str
  #   date_of_birth: date
  #   sex: str
    # Add other demographic columns as needed
  # med:
  #   id: str
  #   date: date
  #   med: str
    # Add other medication columns as needed
  icd:
    id : !pl String
    icd : !pl String
    date : !pl Date
    # Add other ICD columns as needed
  note:
    id : !pl String
    note : !pl String
    date : !pl Date
    # Add other note columns as needed

# Feature extraction parameters
parameters:
  # demographics:
    # extract_columns: ['age', 'sex'] # Columns to extract from demographics
  # med:
  #   names: ['levetiracetam', 'lamotrigine']  # List of medications to search for
  #   time_window: "6mo"  # Time window for medication search (6 months by default)
  icd:
    codes: ['^433', '^434', '^I63', '^I69\.?3']  # List of ICD codes to search for
    time_window: "6mo"  # Time window for ICD code search (6 months by default)
  keywords:
    positive: ['acetaminophen', 'acut infarct', 'acut intracrani hemorrhag', 'acut myocardi infarct', 'adderal', 'advair', 'affect area', 'age brain', 'age head', 'albuterol', 'allergi drug', 'amlodipin', 'aneurysm', 'aortic arch', 'arteri', 'arteri diseas', 'arteri stroke', 'aspirin', 'atorvastatin', 'atrial fibril', 'blood', 'blood clot', 'blood flow', 'blood pressur', 'blood sugar', 'blood sugar diagnost', 'blood work', 'brain', 'bupropion', 'cardiac diseas', 'cardiac tumor', 'cardioembol', 'cardiomyopathi', 'carotid', 'carotid arteri', 'caviti clear', 'cerebr arteri', 'chest pain', 'cholecalciferol', 'chronic pain', 'chronic small', 'chronic small vessel', 'circl willi', 'clear auscult', 'clear auscult bilater', 'codein', 'coronari arteri diseas', 'cva', 'delay releas', 'diabet', 'dyslipidemia', 'embol', 'emerg depart', 'endocard', 'evid fractur', 'evid stenosi', 'extrem edema', 'facial droop', 'flovent', 'fluoxetin', 'fluticason', 'furosemid', 'gray', 'hemorrhag transform', 'histori present', 'histori present ill', 'hydrocodon', 'hyperlipidemia', 'hypertens', 'infarct', 'infarct core', 'intern', 'intern carotid', 'intern carotid arteri', 'intracrani hemorrhag', 'involut chang', 'iron', 'ischem', 'ischem chang', 'ischem diseas', 'lacunar', 'levothyroxin', 'lisinopril', 'losartan', 'low extrem edema', 'm1 cutoff', 'm2 cutoff', 'malign', 'metformin', 'methylphenid', 'metoprolol', 'metoprolol succin er', 'mg po daili', 'neurolog deficit', 'obes', 'obstruct', 'obstruct sleep apnea', 'occlus', 'omeprazol', 'oxycodon', 'oxygen', 'penumbra', 'pressur', 'proair', 'propion', 'recreat drug', 'regular rate', 'regular rate rhythm', 'septic emboli', 'sertralin', 'short breath', 'sleep apnea', 'sleep studi', 'small vessel', 'small vessel ischem', 'sodium', 'stenosi', 'stenosi occlus', 'stroke', 'sulfat', 'thrombosi', 'tia', 'tobacco', 'tobacco use', 'toprol', 'tpa', 'tramadol', 'transient ischem attack', 'trazodon', 'vascular territori', 'vertebr', 'vertebr arteri', 'vessel', 'vessel ischem', 'vessel ischem diseas', 'vitamin', 'vitamin d', 'vitamin d defici', 'warfarin', 'watersh']
    negative: ['no', 'not', 'dont', 'absent', 'ho', 'pmh', 'negat', 'histori', 'unlik', 'without', 'lack', 'defer']
  final_cols: 