model_path: mci_model.joblib
credits: 'Wei R, Buss SS, Milde R, Fernandes M, Sumsion D, Davis E, Kong WY, Xiong Y, Veltink J, Rao S, Westover TM, Petersen L, Turley N, Singh A, Das S, Junior VM, Ghanta M, Gupta A, Kim J, Lam AD, Stone KL, Mignot E, Hwang D, Trotti LM, Clifford GD, Katwa U, Thomas RJ, Mukerji S, Zafar SF, Westover MB, Sun H. Automated phenotyping of mild cognitive impairment and Alzheimer's disease and related dementias using electronic health records. Int J Med Inform. 2025 Aug;200:105917. doi: 10.1016/j.ijmedinf.2025.105917. Epub 2025 Apr 11. PMID: 40222334.'
paper_link: 'https://www.sciencedirect.com/science/article/abs/pii/S1386505625001340'
schema:
  icd:
    id : !pl String
    icd : !pl String
    date : !pl Date
  med:
    id : !pl String
    med : !pl String
    date : !pl Date
  note:
    id : !pl String
    note : !pl String
    date : !pl Date
parameters:
  threshold: 
  icd: ['^F00','^G30\.0','^G30\.1','^G30\.8','^G30\.9','^290\.0','^290\.2.*','^290\.3','^331\.0','^F01\..*','^290\.4.*','^G31\.0','^G31\.01','^G31\.09','^311\.11','^331\.19','^F02\.8.*','^F03\.9.*','^294\.1.*','^294\.2.*','^F06\.7','^331\.83']
  med: ['aricept','donepezil','exelon','rivastigmine','memantine','namenda','namzaric','razadyne','galantamine']
  final_cols: ['icd', 'med', 'note']